### ISSUE TITLE
qwen2 vl

### ISSUE THREAD

**Issue by nj159** [soulteary/dify-with-qwen-vl#1]
Excuse me, where did you find the API key for the qwen2 vl model you are using? I couldn't find qwen2 vl on Alibaba Cloud

**Comment by soulteary** [comment]
maybe you can test vl model here: https://bailian.console.aliyun.com/


<img width="835" alt="image" src="https://github.com/user-attachments/assets/12b77e03-8313-454c-ab9e-9a94060c8867">

**Comment by nj159** [comment]
thank you very much,I'm getting the following error when I run the index4.py now, Ask for your help.
Error for frame 2851: 400, Bad Request
{"code": "invalid_param", "message": "Error checking URL: HTTPConnectionPool(host='127.0.0.1', port=60000): Max retries exceeded with url: /mybucket/extracted_frame_1109.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f05e6a8ea40>: Failed to establish a new connection: [Errno 111] Connection refused'))", "status": 400}
